BattleFrontier_PokemonCenter_1F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_PokemonCenter_1F_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0

BattleFrontier_PokemonCenter_1F_OnTransition:
	setrespawn HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST
	end

BattleFrontier_PokemonCenter_1F_EventScript_Nurse::
	setvar VAR_0x800B, LOCALID_FRONTIER_NURSE
	call Common_EventScript_PkmnCenterNurse
	waitmessage
	waitbuttonpress
	release
	end

BattleFrontier_PokemonCenter_1F_EventScript_SchoolKid::
	msgbox BattleFrontier_PokemonCenter_1F_Text_NeverSeenPokemon, MSGBOX_NPC
	end

BattleFrontier_PokemonCenter_1F_EventScript_Man::
	msgbox BattleFrontier_PokemonCenter_1F_Text_NextStopBattleArena, MSGBOX_NPC
	end

BattleFrontier_PokemonCenter_1F_EventScript_Picnicker::
	msgbox BattleFrontier_PokemonCenter_1F_Text_GoingThroughEveryChallenge, MSGBOX_NPC
	end

BattleFrontier_PokemonCenter_1F_EventScript_Skitty::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SKITTY, CRY_MODE_NORMAL
	msgbox BattleFrontier_PokemonCenter_1F_Text_Skitty, MSGBOX_DEFAULT
	waitmoncry
	release
	end

BattleFrontier_PokemonCenter_1F_Text_NeverSeenPokemon:
.string "เมื่อกี้มีคนใช้โปเกมอนที่\nฉันไม่เคยเห็นมาก่อนเลย.\pอย่างน้อยที่โรงเรียนเทรนเนอร์\nก็ไม่เคยสอนเรื่องมันนะ.\pสงสัยจังว่าจะจับโปเกมอนแบบนั้น\nได้จากที่ไหน.$"

BattleFrontier_PokemonCenter_1F_Text_NextStopBattleArena:
.string "เอาล่ะ! จุดหมายต่อไปคือแบทเทิลอารีนา!\nต้องไปเลือกโปเกมอนที่เหมาะจาก\lระบบจัดเก็บโปเกมอนใน PC ก่อน.$"

BattleFrontier_PokemonCenter_1F_Text_GoingThroughEveryChallenge:
.string "ฮิฮิ… ฉันจะพาเจ้าตัวน้อยนี่\nลุยทุกการท้าประลองเลย!$"

BattleFrontier_PokemonCenter_1F_Text_Skitty:
.string "เอเนโค: เมี้ยววว!$"

