#!/usr/bin/env python3
"""Generate the runtime C metadata include from the canonical Thai CSV tables."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

from thai_font import ROOT


GLYPHS = ROOT / "tools/thai/font/thai_glyph_metadata.csv"
BASES = ROOT / "tools/thai/font/thai_base_metrics.csv"
OUTPUT = ROOT / "src/data/thai_text_metadata.inc"
CLASSES = {
    "BASE": "THAI_CLASS_BASE",
    "LEADING_VOWEL": "THAI_CLASS_LEADING_VOWEL",
    "SPACING_VOWEL": "THAI_CLASS_SPACING_VOWEL",
    "UPPER_VOWEL": "THAI_CLASS_UPPER_VOWEL",
    "LOWER_VOWEL": "THAI_CLASS_LOWER_VOWEL",
    "TONE": "THAI_CLASS_TONE",
    "THAN_THAKHAT": "THAI_CLASS_THAN_THAKHAT",
    "NIKHAHIT": "THAI_CLASS_NIKHAHIT",
    "SARA_AM": "THAI_CLASS_SARA_AM",
    "PUNCTUATION": "THAI_CLASS_PUNCTUATION",
}
SHAPES = {
    "normal": "THAI_SHAPE_NORMAL",
    "tall": "THAI_SHAPE_TALL",
    "wide": "THAI_SHAPE_WIDE",
    "descender": "THAI_SHAPE_DESCENDER",
    "special": "THAI_SHAPE_SPECIAL",
}


def generate() -> str:
    with GLYPHS.open(newline="", encoding="utf-8") as handle:
        glyphs = list(csv.DictReader(handle))
    with BASES.open(newline="", encoding="utf-8") as handle:
        bases = list(csv.DictReader(handle))
    lines = ["// Generated by tools/thai/generate_thai_metadata.py. Do not edit.", ""]
    lines.append("const struct ThaiGlyphInfo gThaiGlyphInfo[THAI_GLYPH_LIMIT] =")
    lines.append("{")
    for row in glyphs:
        glyph_id = int(row["glyph_id"], 0)
        component = int(row["component_id"], 0) if row["component_id"] else 0
        lines.append(
            f"    [0x{glyph_id:03X}] = {{{CLASSES[row['class']]}, {int(row['advance'])}, "
            f"{int(row['mark_x'])}, {int(row['mark_y'])}, {int(row['second_level_y'])}, 0x{component:03X}}},"
        )
    lines.extend(["};", "", "const struct ThaiBaseMetrics gThaiBaseMetrics[] =", "{"])
    for row in bases:
        glyph_id = int(row["glyph_id"], 0)
        lines.append(
            f"    {{0x{glyph_id:03X}, {int(row['advance'])}, {int(row['upper_x'])}, {int(row['upper_y'])}, "
            f"{int(row['lower_x'])}, {int(row['lower_y'])}, {int(row['tone_x'])}, {int(row['tone_y'])}, "
            f"{SHAPES[row['shape_group']]} }},"
        )
    lines.extend(["};", "", "const u16 gThaiBaseMetricsCount = ARRAY_COUNT(gThaiBaseMetrics);", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    generated = generate()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated metadata: {OUTPUT}")
            raise SystemExit(1)
        print(f"generated metadata is current: {OUTPUT}")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT}")
