#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAP_PATH = ROOT / "tools/thai/font/thai_precompose_glyph_map.json"
OUTPUT_PATH = ROOT / "src/data/thai_naming_runtime_map.inc"
EXPECTED_SHA256 = "f993e468d5376f5d85a8081bf8171d637ad7de5bd509e84fc68e95aa757d9599"
EXPECTED_FORMAT = "pokemon-gen3-thai-precompose-full-v1"
EXPECTED_GLYPH_COUNT = 761
Y_OFFSET = -12
FLAGS = 1

# K3A's approved one-byte reservation, now mapped to canonical Unicode rather
# than directly to the legacy normal-font glyph IDs.
COMPACT_TO_CANONICAL = {
    0x37: "ก", 0x38: "ข", 0x39: "ค", 0x3A: "ง", 0x3B: "จ", 0x3C: "ฉ",
    0x3D: "ช", 0x3E: "ซ", 0x3F: "ฌ", 0x40: "ญ", 0x41: "ฎ", 0x42: "ฏ",
    0x43: "ฐ", 0x44: "ฑ", 0x45: "ฒ", 0x46: "ณ", 0x47: "ด", 0x48: "ต",
    0x49: "ถ", 0x4A: "ท", 0x4B: "ธ", 0x4C: "น", 0x4D: "บ", 0x4E: "ป",
    0x4F: "ผ", 0x50: "ฝ", 0x5E: "พ", 0x5F: "ฟ", 0x60: "ภ", 0x61: "ม",
    0x62: "ย", 0x63: "ร", 0x64: "ล", 0x65: "ว", 0x66: "ศ", 0x67: "ษ",
    0x69: "ส", 0x6A: "ห", 0x6B: "ฬ", 0x6C: "อ", 0x6D: "ฮ", 0x6E: "ฆ",
    0x70: "เ", 0x71: "แ", 0x72: "โ", 0x73: "ใ", 0x74: "ไ", 0x75: "ะ",
    0x76: "า", 0x78: "ั", 0x7D: "ิ", 0x7E: "ี", 0x7F: "ึ", 0x80: "ื",
    0x81: "ุ", 0x82: "ู", 0x83: "่", 0x87: "้", 0x88: "๊", 0x89: "๋",
    0x8A: "็", 0x8B: "์", 0x8C: "ํ", 0x8D: "ำ", 0x8E: "ๆ",
}


class GenerationError(ValueError):
    pass


def load_entries() -> list[dict]:
    raw = MAP_PATH.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        raise GenerationError(f"map hash mismatch: expected {EXPECTED_SHA256}, got {digest}")
    data = json.loads(raw)
    glyphs = data.get("glyphs")
    if data.get("format") != EXPECTED_FORMAT:
        raise GenerationError("unexpected production map format")
    if not isinstance(glyphs, list) or len(glyphs) != EXPECTED_GLYPH_COUNT:
        raise GenerationError("unexpected production glyph count")

    reverse = {char: compact for compact, char in COMPACT_TO_CANONICAL.items()}
    if len(reverse) != len(COMPACT_TO_CANONICAL):
        raise GenerationError("duplicate canonical compact mapping")
    seen_names: set[str] = set()
    seen_keys: set[tuple[int, ...]] = set()
    entries = []
    for position, glyph in enumerate(glyphs):
        name = glyph.get("name")
        glyph_id = glyph.get("target_index")
        left = glyph.get("left")
        advance = glyph.get("advance")
        if not isinstance(name, str) or not name or name in seen_names:
            raise GenerationError(f"duplicate or malformed name at entry {position}")
        seen_names.add(name)
        if not isinstance(glyph_id, int) or not 0 <= glyph_id < EXPECTED_GLYPH_COUNT:
            raise GenerationError(f"unsupported glyph ID for {name!r}")
        if not isinstance(left, int) or not -128 <= left <= 127:
            raise GenerationError(f"malformed left bearing for {name!r}")
        if not isinstance(advance, int) or not 0 <= advance <= 255:
            raise GenerationError(f"malformed advance for {name!r}")
        if not all(char in reverse for char in name):
            continue
        key = tuple(reverse[char] for char in name)
        if key in seen_keys:
            raise GenerationError(f"duplicate compact key for {name!r}")
        seen_keys.add(key)
        entries.append({"name": name, "key": key, "glyph": glyph_id, "x": left, "advance": advance})

    # A key may prefix another key; longest-match resolves that deterministically.
    # Equal keys would be ambiguous and were rejected above.
    entries.sort(key=lambda item: (-len(item["key"]), item["key"]))
    if not entries or max(len(item["key"]) for item in entries) > 7:
        raise GenerationError("unexpected reachable cluster length")
    return entries


def render(entries: list[dict]) -> str:
    lines = [
        "// Generated by tools/thai/generate_thai_naming_runtime_map.py; do not edit.",
        f"// Production map SHA-256: {EXPECTED_SHA256}",
        f"#define THAI_NAMING_RUNTIME_MAP_COUNT {len(entries)}",
        "static const struct ThaiNamingRuntimeMapEntry sThaiNamingRuntimeMap[THAI_NAMING_RUNTIME_MAP_COUNT] =",
        "{",
    ]
    for item in entries:
        key = list(item["key"]) + [0] * (7 - len(item["key"]))
        lines.append(
            "    {{%s}, %d, %d, %d, %d, %d, %d}, // %s"
            % (", ".join(f"0x{x:02X}" for x in key), len(item["key"]), item["glyph"],
               item["x"], Y_OFFSET, item["advance"], FLAGS, item["name"])
        )
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render(load_entries())
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != output:
            raise GenerationError(f"generated output is stale: {OUTPUT_PATH}")
        print(f"runtime map check passed: {OUTPUT_PATH} ({output.count(chr(10))} lines)")
    else:
        OUTPUT_PATH.write_text(output, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    try:
        main()
    except (GenerationError, OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"runtime map generation failed: {exc}")
