#include "global.h"
#include "data.h"
#include "constants/moves.h"

/*
 * Generated by tools/thai/generate_move_name_runtime.py
 * Source: tools/thai/translation/move_names_thai.csv
 * Do not edit this file manually.
 */

static const u8 sMoveNameThai_FirePunch[] = _("หมัดไฟ");
static const u8 sMoveNameThai_Scratch[] = _("ข่วน");
static const u8 sMoveNameThai_DoubleKick[] = _("เตะคู่");
static const u8 sMoveNameThai_SandAttack[] = _("สาดทราย");
static const u8 sMoveNameThai_Growl[] = _("คำราม");
static const u8 sMoveNameThai_Ember[] = _("สะเก็ดไฟ");
static const u8 sMoveNameThai_Flamethrower[] = _("พ่นไฟ");
static const u8 sMoveNameThai_Peck[] = _("จิก");
static const u8 sMoveNameThai_FireSpin[] = _("วังวนไฟ");
static const u8 sMoveNameThai_QuickAttack[] = _("จู่โจมเร็ว");
static const u8 sMoveNameThai_FocusEnergy[] = _("รวมพลัง");
static const u8 sMoveNameThai_MirrorMove[] = _("สะท้อนท่า");
static const u8 sMoveNameThai_Slash[] = _("ฟาดฟัน");
static const u8 sMoveNameThai_BlazeKick[] = _("เตะเพลิง");
static const u8 sMoveNameThai_SkyUppercut[] = _("หมัดเสยฟ้า");
static const u8 sMoveNameThai_BulkUp[] = _("เสริมกล้าม");

const u8 *GetMoveName(u16 move)
{
    switch (move)
    {
    case MOVE_FIRE_PUNCH:
        return sMoveNameThai_FirePunch;
    case MOVE_SCRATCH:
        return sMoveNameThai_Scratch;
    case MOVE_DOUBLE_KICK:
        return sMoveNameThai_DoubleKick;
    case MOVE_SAND_ATTACK:
        return sMoveNameThai_SandAttack;
    case MOVE_GROWL:
        return sMoveNameThai_Growl;
    case MOVE_EMBER:
        return sMoveNameThai_Ember;
    case MOVE_FLAMETHROWER:
        return sMoveNameThai_Flamethrower;
    case MOVE_PECK:
        return sMoveNameThai_Peck;
    case MOVE_FIRE_SPIN:
        return sMoveNameThai_FireSpin;
    case MOVE_QUICK_ATTACK:
        return sMoveNameThai_QuickAttack;
    case MOVE_FOCUS_ENERGY:
        return sMoveNameThai_FocusEnergy;
    case MOVE_MIRROR_MOVE:
        return sMoveNameThai_MirrorMove;
    case MOVE_SLASH:
        return sMoveNameThai_Slash;
    case MOVE_BLAZE_KICK:
        return sMoveNameThai_BlazeKick;
    case MOVE_SKY_UPPERCUT:
        return sMoveNameThai_SkyUppercut;
    case MOVE_BULK_UP:
        return sMoveNameThai_BulkUp;
    default:
        if (move >= MOVES_COUNT)
            move = MOVE_NONE;

        return gMoveNames[move];
    }
}
